<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.feirui</groupId>
    <artifactId>oss-spring-boot-starter</artifactId>
    <version>${oss-spring-boot-starter.version}</version>
    <packaging>pom</packaging>
    <name>oss-spring-boot-starter</name>

    <modules>
        <module>oss-file-sdk</module>
        <module>oss-file-manage-mysql</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.plugin.source>17</maven.compiler.plugin.source>
        <maven.compiler.plugin.target>17</maven.compiler.plugin.target>
        <maven.compiler.plugin.encoding>UTF-8</maven.compiler.plugin.encoding>
        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
        <flatten-maven-plugin.version>1.5.0</flatten-maven-plugin.version>

        <!--工程本身版本号-->
        <oss-spring-boot-starter.version>1.0.0</oss-spring-boot-starter.version>

        <spring-boot.version>3.4.7</spring-boot.version>
        <hutool.version>5.8.16</hutool.version>
        <apache.tika.version>3.2.1</apache.tika.version>
        <commons-lang3.version>3.17.0</commons-lang3.version>
        <commons-codec.version>1.17.2</commons-codec.version>
        <commons-fileupload.version>1.5</commons-fileupload.version>
        <commons-collections.version>3.2.2</commons-collections.version>
        <mysql.connector.version>8.0.32</mysql.connector.version>
        <mybatis.spring.boot.version>3.0.4</mybatis.spring.boot.version>
        <druid.spring.boot.version>1.2.16</druid.spring.boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>${apache.tika.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-fileupload</groupId>
                <artifactId>commons-fileupload</artifactId>
                <version>${commons-fileupload.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-collections</groupId>
                <artifactId>commons-collections</artifactId>
                <version>${commons-collections.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${commons-codec.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.spring.boot.version}</version>
            </dependency>
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql.connector.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.spring.boot.version}</version>
            </dependency>

            <dependency>
                <groupId>com.feirui</groupId>
                <artifactId>oss-file-sdk</artifactId>
                <version>${oss-spring-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>com.feirui</groupId>
                <artifactId>oss-file-manage-mysql</artifactId>
                <version>${oss-spring-boot-starter.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.plugin.source}</source>
                    <target>${maven.compiler.plugin.target}</target>
                    <encoding>${maven.compiler.plugin.encoding}</encoding>
                </configuration>
            </plugin>
            <!-- 统一version版本,用于父子模块依赖占位符替换 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.ttf</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
