spring:
  application:
    name: oss-spring-boot-starter
  oss:
    type: local
    aliyun:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: your-access-key-id
      accessKeySecret: your-access-key-secret
      bucketName: your-bucket-name
      folderPrefix: /files
    tencent:
      endpoint: cos.ap-shanghai.myqcloud.com
      accessKey: your-access-key
      secretKey: your-secret-key
      regionName: your-region-name
      bucketName: your-bucket-name
      folderPrefix: /files
    minio:
      endpoint: http://192.168.1.108:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket-name: your-bucket-name
      folder-prefix: /files
    local:
      folder-prefix: /files